package com.bimeh.iranaccounting;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 LinearLayout list; EditText search; ArrayList<Policy> data=new ArrayList<>(); android.content.SharedPreferences sp;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main); list=findViewById(R.id.list);search=findViewById(R.id.search);sp=getSharedPreferences("data",0);load();render();findViewById(R.id.addBtn).setOnClickListener(v->addDialog());findViewById(R.id.reportBtn).setOnClickListener(v->report());search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render();}public void afterTextChanged(android.text.Editable e){}});}
 void addDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(30,10,30,10); EditText no=e("شماره بیمه‌نامه");EditText name=e("نام بیمه‌گذار");EditText total=e("مبلغ کل (تومان)");EditText cash=e("پرداخت نقدی (تومان)");EditText n=e("تعداد اقساط");l.addView(no);l.addView(name);l.addView(total);l.addView(cash);l.addView(n);new AlertDialog.Builder(this).setTitle("ثبت بیمه‌نامه").setView(l).setPositiveButton("ثبت",(d,w)->{try{int cnt=Integer.parseInt(n.getText().toString());long t=Long.parseLong(total.getText().toString());long c=Long.parseLong(cash.getText().toString());data.add(new Policy(no.getText().toString(),name.getText().toString(),t,c,cnt));save();render();}catch(Exception x){Toast.makeText(this,"اطلاعات عددی را صحیح وارد کنید",Toast.LENGTH_SHORT).show();}}).setNegativeButton("انصراف",null).show();}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setInputType(android.text.InputType.TYPE_CLASS_TEXT);x.setPadding(8,14,8,14);return x;}
 void render(){list.removeAllViews();String q=search.getText().toString().trim();for(int i=0;i<data.size();i++){Policy p=data.get(i);if(!q.isEmpty()&&!p.no.contains(q)&&!p.name.contains(q))continue;TextView t=new TextView(this);t.setText("بیمه‌نامه: "+p.no+"\nبیمه‌گذار: "+p.name+"\nکل: "+p.total+" تومان   نقد: "+p.cash+"   مانده: "+p.balance()+"\nاقساط مانده: "+p.remaining());t.setTextSize(16);t.setTextColor(Color.DKGRAY);t.setBackgroundColor(Color.WHITE);t.setPadding(22,20,22,20);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,10);list.addView(t,lp);t.setOnLongClickListener(v->{edit(i);return true;});}}
 void edit(int i){Policy p=data.get(i);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText cash=e("پرداخت جدید (تومان)");l.addView(cash);new AlertDialog.Builder(this).setTitle("ثبت پرداخت / ویرایش").setMessage("مانده فعلی: "+p.balance()+" تومان").setView(l).setPositiveButton("ثبت پرداخت",(d,w)->{try{p.cash+=Long.parseLong(cash.getText().toString());save();render();}catch(Exception x){}}).setNegativeButton("حذف بیمه‌نامه",(d,w)->{data.remove(i);save();render();}).setNeutralButton("انصراف",null).show();}
 void report(){long total=0,paid=0;int rem=0;for(Policy p:data){total+=p.total;paid+=p.cash;rem+=p.remaining();}new AlertDialog.Builder(this).setTitle("گزارش مدیریتی").setMessage("تعداد بیمه‌نامه: "+data.size()+"\nمبلغ کل: "+total+" تومان\nوصول‌شده: "+paid+" تومان\nمانده مطالبات: "+(total-paid)+" تومان\nاقساط مانده: "+rem).setPositiveButton("باشه",null).show();}
 void save(){JSONArray a=new JSONArray();try{for(Policy p:data){JSONObject o=new JSONObject();o.put("no",p.no);o.put("name",p.name);o.put("total",p.total);o.put("cash",p.cash);o.put("count",p.count);a.put(o);}sp.edit().putString("items",a.toString()).apply();}catch(Exception e){}}
 void load(){try{JSONArray a=new JSONArray(sp.getString("items","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);data.add(new Policy(o.getString("no"),o.getString("name"),o.getLong("total"),o.getLong("cash"),o.getInt("count")));}}catch(Exception e){}}
 static class Policy{String no,name;long total,cash;int count;Policy(String n,String s,long t,long c,int k){no=n;name=s;total=t;cash=c;count=k;}long balance(){return Math.max(0,total-cash);}int remaining(){if(count<=0)return 0;long installment=(total)/count; if(installment<=0)return 0;return (int)Math.ceil((double)balance()/installment);}}
}
